<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.SqlServer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CampaignManager.Infrastructure\CampaignManager.Infrastructure.csproj" />
    <ProjectReference Include="..\CampaignManager.ServiceDefaults\CampaignManager.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
