<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Cronos" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CampaignManager.Domain\CampaignManager.Domain.csproj" />
    <ProjectReference Include="..\CampaignManager.Contracts\CampaignManager.Contracts.csproj" />
  </ItemGroup>
</Project>
